baseURL = 'https://exformal.art'
languageCode = 'en-us'
title = 'Exformal Records'
theme  = ["hugo-video", "exformal", "hugo-audio", "hugo-flickity-carousel", "hugo-art-support"]

[[menu.main]]
name = "zones"
url = "/zones"
weight = 1

[[menu.main]]
name = "releases"
url = "/releases"
weight = 2

[[menu.main]]
name = "shop"
url = "https://exformalrecords.bandcamp.com/"
weight = 3

[[menu.main]]
name = "about"
url = "/about"
weight = 4

[[menu.main]]
name = "newsletter"
url = "/newsletter"
weight = 5

# Site parameters
[params]
description = "How slow can you go?"
keywords="diy record label, record label, experimental music, avantgarde music, art"
featuredPostTitle = ''
logo = 'logos/exformal-logo1.png'
defaultImage = 'logos/exformal-logo1.png'

# Colors
primaryColor = "#FF1818"
secondaryColor = "#CCFF00"
textColor = "#212529"
quoteColor = "#666"
backgroundColor = "#F6F6F6"

secondaryBgColor = "#D4D4D4"
secondaryTextColor = "#3c3836"

[params.social]
  instagram = "https://instagram.com/exformalrecords"
  bandcamp = "https://exformalrecords.bandcamp.com/"
  mastodon = "https://mastodon.social/@exformal"
  # mixcloud = "https://www.mixcloud.com/exformal"
