baseURL = 'https://exformal.art'
languageCode = 'en-us'
title = 'Exformal Records'
theme = 'exformal'

[[menu.main]]
name = "shop"
url = "https://exformalrecords.bandcamp.com/"
weight = 1

[[menu.main]]
name = "newsletter"
url = "/pages/newsletter"
weight = 2

# Site parameters
[params]
featuredPostTitle = 'Newsletter'
logo = 'logos/exformal-logo1.png'

# Colors
primaryColor = "#FF1818"
secondaryColor = "#CCFF00"
textColor = "#212529"
quoteColor = "#666"
backgroundColor = "#ffffff"

secondaryBgColor = "#D4D4D4"
secondaryTextColor = "#3c3836"

[params.social]
  instagram = "https://instagram.com/exformalrecords"
  bandcamp = "https://exformalrecords.bandcamp.com/"
  mastodon = "https://mastodon.social/@exformal"
