baseURL = ''
languageCode = 'en-us'
title = 'Exformal Records'
theme = 'exformal-theme'

[[menu.main]]
name = "intro"
url = "/texts/intro"
weight = 1

[[menu.main]]
name = "releases"
url = "/releases"
weight = 2

[[menu.main]]
name = "about"
url = "/pages/about"
weight = 3


# Site parameters
[params]
featuredPostTitle = "Intro"

[params.social]
  instagram = "exformalrecords"
  bandcamp = "exformalrecords"
