baseURL = 'exformal.art'
languageCode = 'en-us'
title = 'Exformal Records'
theme = 'exformal'

[[menu.main]]
name = "intro"
url = "/texts/intro"
weight = 1

[[menu.main]]
name = "releases"
url = "/releases"
weight = 2

[[menu.main]]
name = "about"
url = "/pages/about"
weight = 3

[[menu.main]]
name = "bandcamp"
url = "https://exformalrecords.bandcamp.com/"
weight = 4

# Site parameters
[params]
featuredPostTitle = 'About Exformal'

# Colors
primaryColor = "#FF1818"
secondaryColor = "#CCFF00"
textColor = "#333"
quoteColor = "#666"
backgroundColor = "#fdfdfd"

[params.social]
  instagram = "exformalrecords"
  bandcamp = "exformalrecords"
