baseURL = 'https://exformal.art/'
languageCode = 'en-us'
title = 'Exformal Records'
theme  = ["hugo-video", "exformal", "hugo-audio", "hugo-flickity-carousel", "hugo-art-support"]

[[menu.main]]
name = "ex"
url = "/"
weight = 1

[[menu.main]]
name = "zones"
url = "/zones"
weight = 1

[[menu.main]]
name = "catalogue"
url = "/releases"
weight = 2

[[menu.main]]
name = "artists"
url = "/artists"
weight = 3

[[menu.main]]
name = "shop"
url = "https://exformalrecords.bandcamp.com/"
weight = 4

[[menu.main]]
name = "contact"
url = "/contact"
weight = 5

# Site parameters
[params]
description = "Beneath the pavement, the beach."
keywords="diy record label, record label, experimental music, avantgarde music, ambient, field recording, art"
featuredPostTitle = ''
logo = 'logos/exformal-logo1.png'
defaultImage = '/logos/exformal-logo1.png'
footerText = "Exformal Records is a platform for experimental music, sounds and listening practices."

# Colors
primaryColor = "#FF1818"
secondaryColor = "#CCFF00"
textColor = "#212529"
quoteColor = "#666"
backgroundColor = "#F6F6F6"

secondaryBgColor = "#D4D4D4"
secondaryTextColor = "#3c3836"

[params.social]
  instagram = "https://instagram.com/exformalrecords"
  bandcamp = "https://exformalrecords.bandcamp.com/"
  mastodon = "https://mastodon.social/@exformal"
  # mixcloud = "https://www.mixcloud.com/exformal"
